### ISSUE TITLE
nibabel problem

### ISSUE THREAD

**Issue by michaelf500** [ME-ICA/me-ica#16]
Hello

I'm running meica on a Windows 10 machine, with a bash shell under Windows Subsystem for Linux, with command
`meica.py -d MJF_180_ME_1.nii,MJF_180_ME_2.nii,MJF_180_ME_3.nii -e 14.8,37.98,61.16 --tpattern=seq-z --prefix MJF_180_multiecho`
 
I get the following error message:

++ 3dZcat: AFNI version=AFNI_19.1.25 (Jun 25 2019) [64-bit]
++ output dataset: ./basestack.nii.gz
-- T2* Map Component for ME-ICA v3.1 beta1 --
++ Loading Data
Traceback (most recent call last):
  File "/home/michael/meica/me-ica/meica.libs/t2smap.py", line 335, in <module>
    catd = cat2echos(catim.get_data(),ne)
  File "/home/michael/meica/me-ica/meica.libs/nibabel/spatialimages.py", line 341, in get_data
    return np.asanyarray(self._data)
  File "/home/michael/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 591, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/home/michael/meica/me-ica/meica.libs/nibabel/arrayproxy.py", line 55, in __array__
    self._data = self._read_data()
  File "/home/michael/meica/me-ica/meica.libs/nibabel/arrayproxy.py", line 60, in _read_data
    data = self.header.data_from_fileobj(fileobj)
  File "/home/michael/meica/me-ica/meica.libs/nibabel/analyze.py", line 486, in data_from_fileobj
    data = self.raw_data_from_fileobj(fileobj)
  File "/home/michael/meica/me-ica/meica.libs/nibabel/analyze.py", line 458, in raw_data_from_fileobj
    return array_from_file(shape, dtype, fileobj, offset)
  File "/home/michael/meica/me-ica/meica.libs/nibabel/volumeutils.py", line 502, in array_from_file
    arr.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

Any suggestion appreciated.

Michael

**Comment by benoitberanger** [comment]
Hello Michael,

I just had the same problem not so long ago, and the answer was in the old MEICA repo on bitbucket.
**Try to downgrade Numpy into version 1.10**, it worked for me.
If you need help to install a specific version of python package : https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip

By the way, if you don't know what is `tedana`, you should take a look : https://github.com/ME-ICA/tedana.
This repo is more "futur proof" for multi-echo denoising.

Best,
Benoît

**Comment by michaelf500** [comment]
Hello Benoît

Thanks, going to numpy 1.10 solved the problem. 
Thanks also for the tip off about tedana, I'll have a look.

Best wishes

Michael
