### ISSUE TITLE
Unable to install with python 3 pip

### ISSUE THREAD

**Issue by Aaronearlerichardson** [ME-ICA/me-ica#17]
Here is a copy of the error code:
```
(base) aaron@aaron-VirtualBox:/media/sf_Ubuntu_files$  pip3 install meica
Collecting meica
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/meica/
```

It appears that the url does not work? What should I do? I'd prefer to install the python 3 version if I can.

**Comment by dowdlelt** [comment]
Hi @Aaronearlerichardson, 

Is there a particular reason you are trying to install meica rather than tedana? This repository is considered outdated and is no longer maintained. Development has continued on `tedana`, the core multiecho/ICA processing code. 

You can clone the repository and use it in a somewhat similar fashion. See here for the tedana code, https://github.com/ME-ICA/tedana and here https://tedana.readthedocs.io/en/latest/ for the tedana docs/installation guidelines etc.

The idea is that you would handle preprocessing of the echoes, and then pass the data through to tedana for optimal combination and denoising. This is contrast to the previous usage of MEICA, which performed a number of steps for you. If you would prefer to have the processing done in AFNI, as it was for MEICA, example 12 (and a few others) in the afni_proc.py help may be useful: https://afni.nimh.nih.gov/pub/dist/doc/program_help/afni_proc.py.html

Let me know if this makes sense. If you run into some problems, check the tedana issues or neurostars.org for the tedana flag - someone may have solved that problem previously.
